nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

npmRegistryServer: 'https://registry.yarnpkg.com'

npmScopes:
  bentley:
    npmRegistryServer: 'https://registry.yarnpkg.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
