name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 12.X
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn npm audit

      - run: yarn lint
      - run: yarn lint:copyright ${{ github.workspace }}/*/**.{js,ts,tsx,scss,html}
      - run: yarn build
      - run: yarn build:demo

  visual-test:
    name: Run visual tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 12.X
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn

      - run: yarn install --frozen-lockfile

      # `&` symbol is needed as it prevents Storybook from running endlessly
      - run: yarn build
      - run: yarn build:demo
      - run: yarn test
