name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 18.X
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn npm audit

      - run: yarn lint
      - run: yarn lint:copyright ${{ github.workspace }}/*/**.{js,ts,tsx,scss,html}
      - run: yarn build
      - run: yarn build:demo

      - run: yarn test:ci
      - name: Upload tests artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: tests-results
          path: |
            demo/cypress-visual-report/
            demo/cypress-visual-screenshots/

  deploy:
    name: Deploy demo HTML page
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 18.X
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn build:demo

      - name: Host Demo on GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: ${{ github.workspace }}/demo/dist
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
