name: Publish CSS

on: workflow_dispatch

jobs:
  publish-css:
    name: Publish iTwinUI-layouts-css npm package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 16.X
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - run: yarn install
      - run: yarn build

      - run: yarn npm publish --access public --tag dev
        working-directory: './packages/layouts-css'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_ITWIN }}
