name: Publish React

on: workflow_dispatch

jobs:
  publish-react:
    name: Publish iTwinUI-layouts-react npm package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 16.X
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - run: yarn install
      - run: yarn build

      # Writes token to .yarnrc.yml
      - run: |
          echo npmAuthToken: "$NODE_AUTH_TOKEN" >> ./.yarnrc.yml
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_ITWIN }}
      - run: yarn npm publish --access public
        working-directory: './packages/layouts-react'
